/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.gestion.Location.views;

import app.gestion.Location.dao.HibernateUtil;
import app.gestion.Location.dao.UtilConnection;
import app.gestion.Location.models.Client;
import app.gestion.Location.models.Emprunt;
import app.gestion.Location.models.Exemplaire;
import app.gestion.Location.models.Locataire;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.swing.JRViewer;
import org.hibernate.Session;

/**
 *
 * @author Utilisateur
 */
public class JIEmprunt extends javax.swing.JInternalFrame {

    Client c;
    Emprunt emp;
    Exemplaire e;
    Locataire locat;
    Session s=HibernateUtil.getSession();
    /**
     * Creates new form JIEmprunt
     */
    public JIEmprunt( Locataire locat) {
        this.locat=locat;
        initComponents();
        setSize(944, 91);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelclt = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtclient = new javax.swing.JTextField();
        btnrechclient = new javax.swing.JButton();
        panelInfoclt = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbnomv = new javax.swing.JLabel();
        lbtype = new javax.swing.JLabel();
        cbetatv = new javax.swing.JCheckBox();
        lbprix = new javax.swing.JLabel();
        lbfabricant = new javax.swing.JLabel();
        panelInfoclt1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lbnp = new javax.swing.JLabel();
        lbadresse = new javax.swing.JLabel();
        cbemp = new javax.swing.JCheckBox();
        cbetatcmp = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtmatricule = new javax.swing.JTextField();
        btnrechvoiture = new javax.swing.JButton();
        btnannuler = new javax.swing.JButton();
        btnenregistrer = new javax.swing.JButton();
        txtnbrjour = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lbtotal = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Nouveau Emprunt");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        panelclt.setBackground(new java.awt.Color(255, 204, 0));
        panelclt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setText("CIN Client: ");

        btnrechclient.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        btnrechclient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/gestion/Location/img/search.png"))); // NOI18N
        btnrechclient.setText("Identifier Client");
        btnrechclient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrechclientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelcltLayout = new javax.swing.GroupLayout(panelclt);
        panelclt.setLayout(panelcltLayout);
        panelcltLayout.setHorizontalGroup(
            panelcltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelcltLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103)
                .addComponent(txtclient, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128)
                .addComponent(btnrechclient)
                .addContainerGap(131, Short.MAX_VALUE))
        );
        panelcltLayout.setVerticalGroup(
            panelcltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelcltLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelcltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtclient, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnrechclient, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panelInfoclt.setBackground(new java.awt.Color(255, 204, 0));
        panelInfoclt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("Nom:");

        jLabel3.setText("Type:");

        jLabel4.setText("Prix:");

        jLabel5.setText("Etat:");

        lbnomv.setText("-");

        lbtype.setText("-");

        cbetatv.setEnabled(false);

        lbprix.setText("-");

        lbfabricant.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lbfabricant.setText("-");

        javax.swing.GroupLayout panelInfocltLayout = new javax.swing.GroupLayout(panelInfoclt);
        panelInfoclt.setLayout(panelInfocltLayout);
        panelInfocltLayout.setHorizontalGroup(
            panelInfocltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfocltLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(panelInfocltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelInfocltLayout.createSequentialGroup()
                        .addGroup(panelInfocltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(193, 193, 193)
                        .addGroup(panelInfocltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbetatv, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbprix, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panelInfocltLayout.createSequentialGroup()
                        .addGroup(panelInfocltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(189, 189, 189)
                        .addGroup(panelInfocltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbnomv, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbtype, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbfabricant, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelInfocltLayout.setVerticalGroup(
            panelInfocltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfocltLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelInfocltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbnomv))
                .addGap(18, 18, 18)
                .addGroup(panelInfocltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbtype)
                    .addComponent(lbfabricant))
                .addGap(12, 12, 12)
                .addGroup(panelInfocltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lbprix))
                .addGap(8, 8, 8)
                .addGroup(panelInfocltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(cbetatv))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelInfoclt1.setBackground(new java.awt.Color(255, 204, 0));
        panelInfoclt1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setText("Nom et Prénom:");

        jLabel10.setText("Adresse:");

        jLabel11.setText("Emprunté:");

        jLabel12.setText("Etat du compte:");

        lbnp.setText("-");

        lbadresse.setText("-");

        cbemp.setEnabled(false);
        cbemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbempActionPerformed(evt);
            }
        });

        cbetatcmp.setEnabled(false);

        javax.swing.GroupLayout panelInfoclt1Layout = new javax.swing.GroupLayout(panelInfoclt1);
        panelInfoclt1.setLayout(panelInfoclt1Layout);
        panelInfoclt1Layout.setHorizontalGroup(
            panelInfoclt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoclt1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(panelInfoclt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInfoclt1Layout.createSequentialGroup()
                        .addGroup(panelInfoclt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addGap(143, 143, 143)
                        .addGroup(panelInfoclt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbnp, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbadresse, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelInfoclt1Layout.createSequentialGroup()
                        .addGroup(panelInfoclt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(143, 143, 143)
                        .addGroup(panelInfoclt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbemp, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                            .addComponent(cbetatcmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelInfoclt1Layout.setVerticalGroup(
            panelInfoclt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoclt1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelInfoclt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lbnp))
                .addGap(18, 18, 18)
                .addGroup(panelInfoclt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInfoclt1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInfoclt1Layout.createSequentialGroup()
                        .addComponent(lbadresse)
                        .addGap(18, 18, 18)))
                .addGroup(panelInfoclt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cbemp))
                .addGap(8, 8, 8)
                .addGroup(panelInfoclt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cbetatcmp))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 204, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel8.setText("Matricule:");

        btnrechvoiture.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        btnrechvoiture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/gestion/Location/img/search.png"))); // NOI18N
        btnrechvoiture.setText("Identifier Voiture");
        btnrechvoiture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrechvoitureActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(txtmatricule, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117)
                .addComponent(btnrechvoiture)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtmatricule, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnrechvoiture, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        btnannuler.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        btnannuler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/gestion/Location/img/cancel.png"))); // NOI18N
        btnannuler.setText("Annuler");
        btnannuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnannulerActionPerformed(evt);
            }
        });

        btnenregistrer.setBackground(new java.awt.Color(0, 204, 0));
        btnenregistrer.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        btnenregistrer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/gestion/Location/img/save.png"))); // NOI18N
        btnenregistrer.setText("Enregistrer");
        btnenregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnenregistrerActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel6.setText("Nombre de jour:");

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton1.setText("Total");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel7.setText("=");

        lbtotal.setText("-");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelInfoclt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelInfoclt1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(panelclt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnenregistrer, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnannuler, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(txtnbrjour, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbtotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(panelclt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(panelInfoclt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtnbrjour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbtotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7)))
                                .addGap(39, 39, 39)
                                .addComponent(btnenregistrer, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnannuler, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelInfoclt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbempActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbempActionPerformed

    private void btnrechclientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrechclientActionPerformed
        // TODO add your handling code here:
        c=(Client) s.get(Client.class, txtclient.getText());
         if(c==null){
            JOptionPane.showMessageDialog(null, "Code Client Invalide!","ERROR",JOptionPane.ERROR_MESSAGE);
        }else{
            setSize(944, 297);
            lbnp.setText(c.getNomClt()+" "+c.getPrenom());
            lbadresse.setText(c.getAdresse());
            cbemp.setSelected(c.getEmprunte());
            cbetatcmp.setSelected(c.getEtatCpt());
            
        }if(c.getEmprunte()){
            setSize(944, 263);
        }else{
            setSize(944, 335);
        }
    }//GEN-LAST:event_btnrechclientActionPerformed

    private void btnrechvoitureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrechvoitureActionPerformed
        // TODO add your handling code here:
         e=(Exemplaire) s.get(Exemplaire.class, txtmatricule.getText());
         if(e==null){
            JOptionPane.showMessageDialog(null, "Matricule Invalide!","ERROR",JOptionPane.ERROR_MESSAGE);
        }else{
            setSize(944, 496);
            lbnomv.setText(e.getVoiture().getNomv());
            lbtype.setText(e.getType());
            lbprix.setText(e.getPrix()+"");
            cbetatv.setSelected(e.getEtatEx());
            lbfabricant.setText(e.getVoiture().getFabricants().toString());
            
        }if(c.getEtatCpt()&&e.getEtatEx()){
            setSize(1247, 496);
        }
    }//GEN-LAST:event_btnrechvoitureActionPerformed

    private void btnenregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnenregistrerActionPerformed
        // TODO add your handling code here:
        Calendar cal=Calendar.getInstance();
        cal.add(Calendar.DATE, Integer.parseInt(txtnbrjour.getText()));
        float total;
         total=e.getPrix()*Integer.parseInt(txtnbrjour.getText());
         emp=new Emprunt(0,locat,e,c,new Date(),cal.getTime(),null,total);
        s.beginTransaction();
        s.persist(emp);
        c.setEmprunte(true);
        
        e.setEtatEx(false);
        s.save(c);
        s.save(e);
        s.getTransaction().commit();
        s.flush();
        JOptionPane.showMessageDialog(null, "Emprunt Enregistre avec succes.");
        txtclient.setText("");
        txtmatricule.setText("");
        txtnbrjour.setText("");
        setSize(944, 91);
        
        
        
        try {
            JasperDesign jd=JRXmlLoader.load("C:\\Users\\hp\\Desktop\\ireportLoc\\empfiche.jrxml");
            JasperReport jr=JasperCompileManager.compileReport(jd);
            Map param=new HashMap();
            param.put("idemp", emp.getNumEmp());
            JasperPrint jp=JasperFillManager.fillReport(jr, param, UtilConnection.seConnecter());
            JRViewer view=new JRViewer(jp);
            FrameImpression i=new FrameImpression();
            i.getContentPane().add(view);
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnenregistrerActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        float total;
        total=e.getPrix()*Integer.parseInt(txtnbrjour.getText());
        lbtotal.setText(total+"");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnannulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnannulerActionPerformed
        // TODO add your handling code here:
        hide();
    }//GEN-LAST:event_btnannulerActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        // TODO add your handling code here:
        s.close();
    }//GEN-LAST:event_formInternalFrameClosing

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formInternalFrameOpened

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnannuler;
    private javax.swing.JButton btnenregistrer;
    private javax.swing.JButton btnrechclient;
    private javax.swing.JButton btnrechvoiture;
    private javax.swing.JCheckBox cbemp;
    private javax.swing.JCheckBox cbetatcmp;
    private javax.swing.JCheckBox cbetatv;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbadresse;
    private javax.swing.JLabel lbfabricant;
    private javax.swing.JLabel lbnomv;
    private javax.swing.JLabel lbnp;
    private javax.swing.JLabel lbprix;
    private javax.swing.JLabel lbtotal;
    private javax.swing.JLabel lbtype;
    private javax.swing.JPanel panelInfoclt;
    private javax.swing.JPanel panelInfoclt1;
    private javax.swing.JPanel panelclt;
    private javax.swing.JTextField txtclient;
    private javax.swing.JTextField txtmatricule;
    private javax.swing.JTextField txtnbrjour;
    // End of variables declaration//GEN-END:variables
}
