/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.gestion.Location.views;

import app.gestion.Location.dao.HibernateUtil;
import app.gestion.Location.models.Exemplaire;
import app.gestion.Location.models.Location;
import app.gestion.Location.models.Voiture;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import org.hibernate.Session;

/**
 *
 * @author Utilisateur
 */
public class JIFrameCreerExemplaire extends javax.swing.JInternalFrame {

    Location l;
    Session s;
    ButtonGroup bg;
    /**
     * Creates new form JIFrameCreerExemplaire
     */
    public JIFrameCreerExemplaire(Location l) {
        initComponents();
        this.l=l;
        s=HibernateUtil.getSession();
        bg=new ButtonGroup();
        bg.add(rbauto);
        bg.add(rbmanuel);
        rbmanuel.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbv = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        rbmanuel = new javax.swing.JRadioButton();
        rbauto = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        txtmat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtcolor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtprix = new javax.swing.JTextField();
        btncreer = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 102, 0));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Nouveau Exemplaire");
        setOpaque(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setText("Voiture:");

        cbv.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        cbv.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "choix" }));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setText("Type:");

        rbmanuel.setBackground(new java.awt.Color(255, 204, 0));
        rbmanuel.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        rbmanuel.setText("Manuel");

        rbauto.setBackground(new java.awt.Color(255, 204, 0));
        rbauto.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        rbauto.setText("Automatique");
        rbauto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbautoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel3.setText("Matricule:");

        txtmat.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel4.setText("Couleur:");

        txtcolor.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel5.setText("Prix:");

        txtprix.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        btncreer.setBackground(new java.awt.Color(51, 204, 0));
        btncreer.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btncreer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/gestion/Location/img/add emprunt.png"))); // NOI18N
        btncreer.setText("Creer l'Exemplaire");
        btncreer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(117, 117, 117)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbmanuel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(107, 107, 107)
                                .addComponent(rbauto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtmat, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbv, javax.swing.GroupLayout.Alignment.LEADING, 0, 181, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtprix, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                                .addComponent(txtcolor, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(btncreer, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(211, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtmat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rbmanuel)
                    .addComponent(rbauto))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtcolor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtprix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btncreer, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbautoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbautoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbautoActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
         List<Voiture> lv=s.createQuery("From Voiture").list();
        for(Voiture v:lv){
            cbv.addItem(v);
        }
    }//GEN-LAST:event_formInternalFrameOpened

    private void btncreerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreerActionPerformed
        // TODO add your handling code here:

        s.beginTransaction();
        Voiture v =(Voiture) cbv.getSelectedItem();
        Exemplaire ex=new Exemplaire();
        ex.setVoiture(v);
        ex.setColor(txtcolor.getText());
        ex.setPrix(Float.valueOf(txtprix.getText()));
        ex.setMatricule(txtmat.getText());
        ex.setLocation(l);
        ex.setEtatEx(true);
        if(rbmanuel.isSelected()){
            ex.setType("manuel");
        }else if(rbauto.isSelected()){
            ex.setType("automatique");
        }
 
        s.save(ex);
        s.getTransaction().commit();
        JOptionPane.showMessageDialog(null, "Exemplaire cree avec succes.");
        txtcolor.setText("");
        txtprix.setText("");
        txtmat.setText("");
        cbv.setSelectedIndex(0);
        rbmanuel.setSelected(true);
    }//GEN-LAST:event_btncreerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncreer;
    private javax.swing.JComboBox cbv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rbauto;
    private javax.swing.JRadioButton rbmanuel;
    private javax.swing.JTextField txtcolor;
    private javax.swing.JTextField txtmat;
    private javax.swing.JTextField txtprix;
    // End of variables declaration//GEN-END:variables
}
