/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.gestion.Location.views;

import app.gestion.Location.dao.HibernateUtil;
import app.gestion.Location.models.Client;
import app.gestion.Location.models.Emprunt;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 *
 * @author Utilisateur
 */
public class JIGererClient extends javax.swing.JInternalFrame {

    Session s;
    DefaultTableModel df=null;
    Client c=null;
    /**
     * Creates new form JIGererClient
     */
    public JIGererClient() {
        s=HibernateUtil.getSession();
        initComponents();
        setSize(1118, 137);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtcin = new javax.swing.JTextField();
        btnIdentifierclt = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbnp = new javax.swing.JLabel();
        lbadr = new javax.swing.JLabel();
        cbemp = new javax.swing.JCheckBox();
        cbetatcmp = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableclt = new javax.swing.JTable();
        btnres = new javax.swing.JButton();
        btnbloc = new javax.swing.JButton();
        btndebloc = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Gestion de (Client/Emprunt)");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBackground(new java.awt.Color(255, 204, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setText("CIN:");

        btnIdentifierclt.setBackground(new java.awt.Color(0, 102, 255));
        btnIdentifierclt.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        btnIdentifierclt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/gestion/Location/img/search.png"))); // NOI18N
        btnIdentifierclt.setText("Identifier Client");
        btnIdentifierclt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIdentifiercltActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(txtcin, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123)
                .addComponent(btnIdentifierclt)
                .addGap(23, 23, 23))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtcin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIdentifierclt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 204, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("Nom et Prénom:");

        jLabel3.setText("Adresse:");

        jLabel4.setText("Emprunté:");

        jLabel5.setText("Etat du compte:");

        lbnp.setText("-");

        lbadr.setText("-");

        cbemp.setEnabled(false);

        cbetatcmp.setEnabled(false);

        tableclt.setBackground(new java.awt.Color(255, 153, 0));
        tableclt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tableclt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id emprunte", "Fabricant", "Voiture", "Matricule", "Type", "Couleur", "Date d'emprunt", "Date rest prevue", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableclt);
        if (tableclt.getColumnModel().getColumnCount() > 0) {
            tableclt.getColumnModel().getColumn(7).setResizable(false);
        }

        btnres.setBackground(new java.awt.Color(0, 204, 0));
        btnres.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        btnres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/gestion/Location/img/return.png"))); // NOI18N
        btnres.setText("Restituer");
        btnres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresActionPerformed(evt);
            }
        });

        btnbloc.setBackground(new java.awt.Color(255, 0, 0));
        btnbloc.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        btnbloc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/gestion/Location/img/lock.png"))); // NOI18N
        btnbloc.setText("Bloquer le Compte");
        btnbloc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnblocActionPerformed(evt);
            }
        });

        btndebloc.setBackground(new java.awt.Color(0, 0, 255));
        btndebloc.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        btndebloc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/gestion/Location/img/key.png"))); // NOI18N
        btndebloc.setText("Debloquer le Compte");
        btndebloc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeblocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(95, 95, 95)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbadr, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cbetatcmp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbemp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 236, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbnp, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                        .addGap(239, 239, 239)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnbloc, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnres, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndebloc))
                .addGap(39, 39, 39))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbnp)
                    .addComponent(btnres, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lbadr))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(cbemp)))
                    .addComponent(btndebloc, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(cbetatcmp)
                        .addComponent(jLabel5))
                    .addComponent(btnbloc, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 332, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIdentifiercltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIdentifiercltActionPerformed
        // TODO add your handling code here:
        c=(Client) s.get(Client.class, txtcin.getText());
        if(c==null){
            JOptionPane.showMessageDialog(null, "CIN invalide!");
        }else{
            lbnp.setText(c.getNomClt()+" "+c.getPrenom());
            lbadr.setText(c.getAdresse());
            cbemp.setSelected(c.getEmprunte());
            cbetatcmp.setSelected(c.getEtatCpt());
            df=(DefaultTableModel) tableclt.getModel();
            df.setRowCount(0);
            for(Emprunt e:c.getEmprunts()){
                if(e.getDaterestReel()==null){
                df.addRow(new Object[]{e.getNumEmp(),e.getExemplaire().getVoiture().getFabricants(),e.getExemplaire().getVoiture().getNomv(),
                e.getExemplaire().getMatricule(),e.getExemplaire().getType(),e.getExemplaire().getColor(),e.getDateEmp(),e.getDaterestPrevu(),e.getTotal()});
                }
            }
            setSize(1118, 520);
        }
    }//GEN-LAST:event_btnIdentifiercltActionPerformed

    private void btnresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresActionPerformed
        // TODO add your handling code here:
        int rep=JOptionPane.showConfirmDialog(null, "Voulez vous restituer cette voiture?","Confirmation",JOptionPane.YES_NO_OPTION);
        if(rep==JOptionPane.YES_OPTION){
                s.beginTransaction();      
                int idemp=Integer.parseInt(df.getValueAt(0, 0).toString());
                Emprunt e=(Emprunt) s.get(Emprunt.class, idemp);
                s.delete(e);
                c.setEmprunte(false);
                c.setEtatCpt(true);              
                e.getExemplaire().setEtatEx(true);
                df.removeRow(0);
                c.getEmprunts().remove(e);            
                s.save(c);
                s.getTransaction().commit();
                s.flush();
            JOptionPane.showMessageDialog(null, "restituer avec succes.");
        }
    }//GEN-LAST:event_btnresActionPerformed

    private void btnblocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnblocActionPerformed
        // TODO add your handling code here:
        int rep=JOptionPane.showConfirmDialog(null, "Voullez vous bien bloquer le compte?","Confirmation",JOptionPane.YES_NO_OPTION);
        if(rep==JOptionPane.YES_OPTION){
            c.setEtatCpt(false);
            Transaction tx=s.beginTransaction();
            s.save(c);
            tx.commit();
            cbetatcmp.setSelected(false);
            JOptionPane.showMessageDialog(null, "Compte bloque avec succes.");
        }
    }//GEN-LAST:event_btnblocActionPerformed

    private void btndeblocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeblocActionPerformed
        // TODO add your handling code here:
        int rep=JOptionPane.showConfirmDialog(null, "Voullez vous bien debloquer le compte?","Confirmation",JOptionPane.YES_NO_OPTION);
        if(rep==JOptionPane.YES_OPTION){
            c.setEtatCpt(true);
            Transaction tx=s.beginTransaction();
            s.save(c);
            tx.commit();
            cbetatcmp.setSelected(true);
            JOptionPane.showMessageDialog(null, "Compte debloque avec succes.");
        }
    }//GEN-LAST:event_btndeblocActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formInternalFrameOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIdentifierclt;
    private javax.swing.JButton btnbloc;
    private javax.swing.JButton btndebloc;
    private javax.swing.JButton btnres;
    private javax.swing.JCheckBox cbemp;
    private javax.swing.JCheckBox cbetatcmp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbadr;
    private javax.swing.JLabel lbnp;
    private javax.swing.JTable tableclt;
    private javax.swing.JTextField txtcin;
    // End of variables declaration//GEN-END:variables
}
