/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.gestion.Location.views;

import app.gestion.Location.dao.HibernateUtil;
import app.gestion.Location.models.Emprunt;
import app.gestion.Location.models.Exemplaire;
import app.gestion.Location.models.Fabricant;
import app.gestion.Location.models.Location;
import app.gestion.Location.models.Voiture;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Query;
import org.hibernate.Session;

/**
 *
 * @author Utilisateur
 */
public class JIRechercherVoiture extends javax.swing.JInternalFrame {

    Session s=null;
    /**
     * Creates new form JIRechercherVoiture
     */
    public JIRechercherVoiture() {
        initComponents();
         s=HibernateUtil.getSession();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbv = new javax.swing.JCheckBox();
        txtvoiture = new javax.swing.JTextField();
        cbf = new javax.swing.JCheckBox();
        txtfabricant = new javax.swing.JTextField();
        btnrechercher = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablev = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 102, 0));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Rechercher");
        setOpaque(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cbv.setBackground(new java.awt.Color(255, 204, 0));
        cbv.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        cbv.setText("Voiture:");

        txtvoiture.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N

        cbf.setBackground(new java.awt.Color(255, 204, 0));
        cbf.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        cbf.setText("Fabricant:");
        cbf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbfActionPerformed(evt);
            }
        });

        txtfabricant.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N

        btnrechercher.setBackground(new java.awt.Color(0, 102, 255));
        btnrechercher.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btnrechercher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/gestion/Location/img/search2.png"))); // NOI18N
        btnrechercher.setText("Rechercher");
        btnrechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrechercherActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbv)
                        .addGap(18, 18, 18)
                        .addComponent(txtvoiture))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtfabricant)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(btnrechercher)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbv)
                    .addComponent(txtvoiture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbf)
                    .addComponent(txtfabricant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addComponent(btnrechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 204, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tablev.setBackground(new java.awt.Color(255, 153, 0));
        tablev.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tablev.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Voiture", "Fabricant", "Matricule", "Type", "Couleur", "Prix", "Location", "Disponibilité"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablev);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 883, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbfActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_cbfActionPerformed

    private void btnrechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrechercherActionPerformed
        // TODO add your handling code here:
         DefaultTableModel df=(DefaultTableModel) tablev.getModel();
        df.setRowCount(0);
        String req="Select ex from Exemplaire ex join ex.voiture v join v.fabricants f where ";
        int n=0;
        
        if(cbv.isSelected()){
            n++;
            req+=" lower(ex.voiture.nomv) like lower('%"+txtvoiture.getText()+"%') ";
            if(cbf.isSelected()){
                req+=" and lower(f.nomf) like lower('%"+txtfabricant.getText()+"%') ";
            }
            }else if(cbf.isSelected()){
            n++;
             req+=" lower(f.nomf) like lower('%"+txtfabricant.getText()+"%') ";
        }if(n==0 || (txtvoiture.getText().equals("") && txtfabricant.getText().equals(""))){
            JOptionPane.showMessageDialog(null, "Veuillez cocher un critere de recherche et remplir les zones de textes.");
            }else{
            Query q=s.createQuery(req);
            List<Exemplaire> l=q.list();
            for(Exemplaire e:l){
                df.addRow(new Object[]{e.getVoiture().getNomv(),e.getVoiture().getFabricants(),e.getMatricule(),e.getType(),
                e.getColor(),e.getPrix(),e.getLocation(),(e.getEtatEx()?"Disponible":"Indisponible")});
            }
        }
    }//GEN-LAST:event_btnrechercherActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        DefaultTableModel df=(DefaultTableModel) tablev.getModel();
        String req="Select ex from Exemplaire ex join ex.voiture v join v.fabricants f  ";
        Query q=s.createQuery(req);
            List<Exemplaire> l=q.list();
            for(Exemplaire e:l){
                df.addRow(new Object[]{e.getVoiture().getNomv(),e.getVoiture().getFabricants(),e.getMatricule(),e.getType(),
                e.getColor(),e.getPrix(),e.getLocation(),(e.getEtatEx()?"Disponible":"Indisponible")});
            }
    }//GEN-LAST:event_formInternalFrameOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnrechercher;
    private javax.swing.JCheckBox cbf;
    private javax.swing.JCheckBox cbv;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablev;
    private javax.swing.JTextField txtfabricant;
    private javax.swing.JTextField txtvoiture;
    // End of variables declaration//GEN-END:variables
}
