package app.gestion.Location.models;



import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Client generated by hbm2java
 */
@Entity
@Table(name="CLIENT"
    ,schema="LOC"
)
public class Client  implements java.io.Serializable {


     private String cin;
     private Location location;
     private String nomClt;
     private String prenom;
     private String adresse;
     private Boolean emprunte;
     private Boolean etatCpt;
     private Set<Emprunt> emprunts = new HashSet<Emprunt>(0);

    public Client() {
    }

	
    public Client(String cin) {
        this.cin = cin;
    }
    public Client(String cin, Location location, String nomClt, String prenom, String adresse, Boolean emprunte, Boolean etatCpt, Set<Emprunt> emprunts) {
       this.cin = cin;
       this.location = location;
       this.nomClt = nomClt;
       this.prenom = prenom;
       this.adresse = adresse;
       this.emprunte = emprunte;
       this.etatCpt = etatCpt;
       this.emprunts = emprunts;
    }
   
     @Id 

    
    @Column(name="CIN", unique=true, nullable=false, length=10)
    public String getCin() {
        return this.cin;
    }
    
    public void setCin(String cin) {
        this.cin = cin;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="NUM_LOC")
    public Location getLocation() {
        return this.location;
    }
    
    public void setLocation(Location location) {
        this.location = location;
    }

    
    @Column(name="NOM_CLT", length=30)
    public String getNomClt() {
        return this.nomClt;
    }
    
    public void setNomClt(String nomClt) {
        this.nomClt = nomClt;
    }

    
    @Column(name="PRENOM", length=30)
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

    
    @Column(name="ADRESSE", length=30)
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }

    
    @Column(name="EMPRUNTE", precision=1, scale=0)
    public Boolean getEmprunte() {
        return this.emprunte;
    }
    
    public void setEmprunte(Boolean emprunte) {
        this.emprunte = emprunte;
    }

    
    @Column(name="ETAT_CPT", precision=1, scale=0)
    public Boolean getEtatCpt() {
        return this.etatCpt;
    }
    
    public void setEtatCpt(Boolean etatCpt) {
        this.etatCpt = etatCpt;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="client")
    public Set<Emprunt> getEmprunts() {
        return this.emprunts;
    }
    
    public void setEmprunts(Set<Emprunt> emprunts) {
        this.emprunts = emprunts;
    }




}


