package app.gestion.Location.models;
// Generated 10-f�vr.-2020 1:53:13 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Emprunt generated by hbm2java
 */
@Entity
@Table(name="EMPRUNT"
    ,schema="LOC"
)
@SequenceGenerator(name = "seq_emp",sequenceName = "seq_emp")
public class Emprunt  implements java.io.Serializable {


     private int numEmp;
     private Locataire locataire;
     private Exemplaire exemplaire;
     private Client client;
     private Date dateEmp;
     private Date daterestPrevu;
     private Date daterestReel;
     private float total;

    public Emprunt() {
    }

	
    public Emprunt(int numEmp) {
        this.numEmp = numEmp;
    }
    public Emprunt(int numEmp, Locataire locataire, Exemplaire exemplaire, Client client, Date dateEmp, Date daterestPrevu, Date daterestReel, float total) {
       this.numEmp = numEmp;
       this.locataire = locataire;
       this.exemplaire = exemplaire;
       this.client = client;
       this.dateEmp = dateEmp;
       this.daterestPrevu = daterestPrevu;
       this.daterestReel = daterestReel;
       this.total = total;
    }
   
     @Id 

    @GeneratedValue(generator = "seq_emp",strategy = GenerationType.SEQUENCE)
    @Column(name="NUM_EMP", unique=true, nullable=false, precision=7, scale=0)
    public int getNumEmp() {
        return this.numEmp;
    }
    
    public void setNumEmp(int numEmp) {
        this.numEmp = numEmp;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_LOCAT")
    public Locataire getLocataire() {
        return this.locataire;
    }
    
    public void setLocataire(Locataire locataire) {
        this.locataire = locataire;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MATRICULE")
    public Exemplaire getExemplaire() {
        return this.exemplaire;
    }
    
    public void setExemplaire(Exemplaire exemplaire) {
        this.exemplaire = exemplaire;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CIN")
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_EMP", length=7)
    public Date getDateEmp() {
        return this.dateEmp;
    }
    
    public void setDateEmp(Date dateEmp) {
        this.dateEmp = dateEmp;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATEREST_PREVU", length=7)
    public Date getDaterestPrevu() {
        return this.daterestPrevu;
    }
    
    public void setDaterestPrevu(Date daterestPrevu) {
        this.daterestPrevu = daterestPrevu;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATEREST_REEL", length=7)
    public Date getDaterestReel() {
        return this.daterestReel;
    }
    
    public void setDaterestReel(Date daterestReel) {
        this.daterestReel = daterestReel;
    }

    
    @Column(name="TOTAL", precision=6)
    public float getTotal() {
        return this.total;
    }
    
    public void setTotal(float total) {
        this.total = total;
    }




}


