package app.gestion.Location.models;
// Generated 10-f�vr.-2020 1:53:13 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Exemplaire generated by hbm2java
 */
@Entity
@Table(name="EXEMPLAIRE"
    ,schema="LOC"
)
public class Exemplaire  implements java.io.Serializable {


     private String matricule;
     private Voiture voiture;
     private Location location;
     private String type;
     private String color;
     private float prix;
     private Boolean etatEx;
     private Set<Emprunt> emprunts = new HashSet<Emprunt>(0);

    public Exemplaire() {
    }

	
    public Exemplaire(String matricule) {
        this.matricule = matricule;
    }
    public Exemplaire(String matricule, Voiture voiture, Location location, String type, String color, float prix, Boolean etatEx, Set<Emprunt> emprunts) {
       this.matricule = matricule;
       this.voiture = voiture;
       this.location = location;
       this.type = type;
       this.color = color;
       this.prix = prix;
       this.etatEx = etatEx;
       this.emprunts = emprunts;
    }
   
     @Id 

    
    @Column(name="MATRICULE", unique=true, nullable=false, length=10)
    public String getMatricule() {
        return this.matricule;
    }
    
    public void setMatricule(String matricule) {
        this.matricule = matricule;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDV")
    public Voiture getVoiture() {
        return this.voiture;
    }
    
    public void setVoiture(Voiture voiture) {
        this.voiture = voiture;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="NUM_LOC")
    public Location getLocation() {
        return this.location;
    }
    
    public void setLocation(Location location) {
        this.location = location;
    }

    
    @Column(name="TYPE", length=20)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="COLOR", length=20)
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }

    
    @Column(name="PRIX", precision=6)
    public float getPrix() {
        return this.prix;
    }
    
    public void setPrix(float prix) {
        this.prix = prix;
    }

    
    @Column(name="ETAT_EX", precision=1, scale=0)
    public Boolean getEtatEx() {
        return this.etatEx;
    }
    
    public void setEtatEx(Boolean etatEx) {
        this.etatEx = etatEx;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="exemplaire")
    public Set<Emprunt> getEmprunts() {
        return this.emprunts;
    }
    
    public void setEmprunts(Set<Emprunt> emprunts) {
        this.emprunts = emprunts;
    }




}


