package app.gestion.Location.models;
// Generated 10-f�vr.-2020 1:53:13 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Fabricant generated by hbm2java
 */
@Entity
@Table(name="FABRICANT"
    ,schema="LOC"
)
public class Fabricant  implements java.io.Serializable {


     private short idf;
     private String nomf;
     private Set<Voiture> voitures = new HashSet<Voiture>(0);

    public Fabricant() {
    }

	
    public Fabricant(short idf) {
        this.idf = idf;
    }
    public Fabricant(short idf, String nomf, Set<Voiture> voitures) {
       this.idf = idf;
       this.nomf = nomf;
       this.voitures = voitures;
    }
   
     @Id 

    
    @Column(name="IDF", unique=true, nullable=false, precision=4, scale=0)
    public short getIdf() {
        return this.idf;
    }
    
    public void setIdf(short idf) {
        this.idf = idf;
    }

    
    @Column(name="NOMF", length=30)
    public String getNomf() {
        return this.nomf;
    }
    
    public void setNomf(String nomf) {
        this.nomf = nomf;
    }

@ManyToMany(fetch=FetchType.LAZY, mappedBy="fabricants")
    public Set<Voiture> getVoitures() {
        return this.voitures;
    }
    
    public void setVoitures(Set<Voiture> voitures) {
        this.voitures = voitures;
    }

    @Override
    public String toString() {
        return nomf + "";
    }




}


