package app.gestion.Location.models;



import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Locataire generated by hbm2java
 */
@Entity
@Table(name="LOCATAIRE"
    ,schema="LOC"
)
public class Locataire  implements java.io.Serializable {


     private short idLocat;
     private Location location;
     private Compte compte;
     private String nomLocat;
     private String prenomLocat;
     private Set<Emprunt> emprunts = new HashSet<Emprunt>(0);

    public Locataire() {
    }

	
    public Locataire(short idLocat) {
        this.idLocat = idLocat;
    }
    public Locataire(short idLocat, Location location, Compte compte, String nomLocat, String prenomLocat, Set<Emprunt> emprunts) {
       this.idLocat = idLocat;
       this.location = location;
       this.compte = compte;
       this.nomLocat = nomLocat;
       this.prenomLocat = prenomLocat;
       this.emprunts = emprunts;
    }
   
     @Id 

    
    @Column(name="ID_LOCAT", unique=true, nullable=false, precision=4, scale=0)
    public short getIdLocat() {
        return this.idLocat;
    }
    
    public void setIdLocat(short idLocat) {
        this.idLocat = idLocat;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="NUM_LOC")
    public Location getLocation() {
        return this.location;
    }
    
    public void setLocation(Location location) {
        this.location = location;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="LOGIN")
    public Compte getCompte() {
        return this.compte;
    }
    
    public void setCompte(Compte compte) {
        this.compte = compte;
    }

    
    @Column(name="NOM_LOCAT", length=30)
    public String getNomLocat() {
        return this.nomLocat;
    }
    
    public void setNomLocat(String nomLocat) {
        this.nomLocat = nomLocat;
    }

    
    @Column(name="PRENOM_LOCAT", length=30)
    public String getPrenomLocat() {
        return this.prenomLocat;
    }
    
    public void setPrenomLocat(String prenomLocat) {
        this.prenomLocat = prenomLocat;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="locataire")
    public Set<Emprunt> getEmprunts() {
        return this.emprunts;
    }
    
    public void setEmprunts(Set<Emprunt> emprunts) {
        this.emprunts = emprunts;
    }




}


